@echo off
:: Only backup files.
:: For Windows Task Scheduler.
:: Or compile this file to invisible_program.exe (bat to exe)
SET dest=%SystemRoot%\System32\config\RegBack\& :: destination backup files for restore

echo Current hive: HKEY_CLASSES_ROOT... & REG EXPORT HKEY_CLASSES_ROOT %dest%HCR /y & echo ...
echo Current hive: HKEY_CURRENT_USER... & REG EXPORT HKEY_CURRENT_USER %dest%HCU /y & echo ...
echo Current hive: HKEY_LOCAL_MACHINE... & REG EXPORT HKEY_LOCAL_MACHINE %dest%HLM /y & echo ...
echo Current hive: HKEY_USERS... & REG EXPORT HKEY_USERS %dest%HU /y & echo ...
echo Current hive: HKEY_USERS... & REG EXPORT HKEY_CURRENT_CONFIG %dest%HCC /y & echo ...
exit
